### ISSUE TITLE
Wrong name used for config/PID lookup

### ISSUE THREAD

**Issue by notverymoe** [kurikaesu/xp-pen-userland-config-util#1]
The GUI doesn't appear to work with the latest version of the userland driver. I believe this is because the scripts reference `xp_pen_userland` for the config and PID lookup. Changing them to reference `userspace_tablet_driver_daemon` instead on lines 88, 95 & 99 of configuration_window.py seems to restore function.

(PS Great work on both of these projects!)

**Comment by kurikaesu** [comment]
Thanks for opening this issue. This repository isn't being updated anymore as I've changed the GUI implementation over to a Kotlin one: https://github.com/kurikaesu/userspace-tablet-driver-gui

Please use the Kotlin version as it is the most up to date. Alternatively if you would like to send me a pull request here to fix the issues you've found then I would be happy to accept them.

**Comment by notverymoe** [comment]
Ah, I see I followed an old link on another issue, my bad! :)
